project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - calendar.qmd
    - people.qmd
    - things.qmd

website:
  title: "NARC Field Day 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - calendar.qmd
      - people.qmd
      - things.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

