project:
  type: website

website:
  title: "field-day"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - calendar.qmd
      - people.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

