---
title: "Calendar"
---

## About

This page describes some of the specific actions that need to be taken leading up to and on Field Day.

## May 2026

- [X] Add info to ARRL Field Day website. (W3TM)
- [X] Create Field Day [budget](https://docs.google.com/spreadsheets/d/19nvy50xuPFYsw2WEzRyj7bWH7aAacUKBGc_DS8plzqY/edit?usp=sharing) (W3TM)
    - [X] Food & drink budget.
    - [X] Porta-Potty estimate. (K3CWP)
    - [X] Equipment estimate.
    - [X] PR and supply estimate.
- [X] Secure NARC BoD budget approval. (W3TM & K3YV).


## June 2026

### 4 weeks out

- [X] Add event to web-based activity calendars.
    - [x] WSPU activity calendar. (W3TM)
    - [x] State College dot com calendar. (H3LP)
- [ ] Send invitations to other groups
    - [x] Pack 67 Cub Scouts. (W3TM)
    - [ ] Troop XX Scouts (K3IWI per 2026-06-19 text)
    - [x] Troop 375 (KD3CCP per email)
    - [ ] Central PA Observers. (W3TM)
    - [x] Announce on ARES net (W3EDP)
    - [ ] new-faculty-l (W3TM)
- [ ] Draft and send invitations to elected officials. (H3LP)
- [x] Draft and send invitation to served agency official. (W3TM)
- [x] Schedule Porta-Potty delivery (K3CWP).
  - [x] Robinson booked 2026-06-08 (K3CWP).
- [X] Distribute [member survey](survey.qmd) (W3TM).
- [ ] Configure & test computers (W3TM)
    - [X] Station 1 (NARC1)
      - [X] WSJT-X
      - [X] JS8Call
      - [X] Winlink + Vara HF
      - [ ] fldigi
      - [X] VarAC
      - [ ] SSTV
      - [X] ACLog Field Day
    - [ ] Station 2 (NARC2)
      - [x] WSJT-X
      - [x] JS8Call
      - [x] Winlink + Vara HF
      - [ ] fldigi
      - [ ] VarAC
      - [ ] SSTV
      - [x] ACLog Field Day
    - [ ] Station 3 (NARC3)
      - [x] WSJT-X
      - [x] JS8Call
      - [ ] Winlink + Vara HF
      - [ ] fldigi
      - [ ] VarAC
      - [ ] SSTV
      - [x] ACLog Field Day
      
### 3 weeks out 

- [x] Get budget approval from membership at 2026-06-09 meeting (W3TM)
- [ ] Draft press release and send to media outlets. (H3LP)
- [x] Evaluate survey results; assign volunteers to teams. (W3TM)
- [ ] Send emails to specific volunteer teams.
    - [x] Food. (W3TM; 2026-06-16)
    - [ ] Ed Activity. (H3LP)
    - [ ] PR. (H3LP)
    - [x] Set-up (W3TM; 2026-06-16)
- [X] Capture & save to removable HD installers & manuals (W3TM)

### 2 weeks out

- [x] Test networked logging on NARC1 (N3LI)
    - [x] Phone
    - [ ] CW
    - [x] WSJT-X
    - [x] fldigi
    - [ ] VarAC (optional)
    - [ ] JS8Call (optional)
- [ ] Test networked logging on NARC2 (N3LI)
    - [x] Phone
    - [ ] CW
    - [x] WSJT-X
    - [x] fldigi
    - [ ] VarAC (optional)
    - [ ] JS8Call (optional)


### Week of event 

- [ ] Order food
  - [ ] Order lunch for Saturday from Jersey Mike's
  - [ ] Order dinner Saturday from Papa John's or Pizza Mia
  - [ ] Breakfast Sunday from Rick & Michelle
- [ ] Buy food and drink
  - [ ] Water & soda
  - [ ] Coffee
    - [ ] Bag/ground
    - [ ] Pods
  - [ ] Chips
  - [ ] Cookies
  - [ ] Fruit
  - [ ] Dogs, buns, fixins
- [ ] Assess supplies (W3TM)
  - [ ] Paper goods
  - [ ] Cups
  - [ ] Utencils
  - [ ] Napkins
  - [ ] Paper towels
  - [ ] Trash bags
- Buy needed supplies
  - [ ] Septic-safe toilet paper (Bring from mountaintop)
  - [ ] Cleaning wipes (mics, keyboards, mice, headsets, CW paddles)
<!-- - [ ] Clean-up station interior -->
<!--   - [ ] Dust or vacuum all surfaces -->
<!--   - [ ] Sweep, vacuum, & mop -->
<!--   - [ ] Move excess gear from shack to shed -->
<!--   - [ ] Clean cooler -->
- [ ] Add Field Day indicator to W3TM-10 APRS I-Gate
- [ ] Confirm Friday & Saturday set-up times
- [x] Pull/pack gear at mountaintop (W3TM; W3EDP on 2026-06-20)
  - [x] Bin 1 (teal): Station 1
    - Radio & power cable
    - Hand mic, desk mic, foot switch
    - CW paddles
    - 2x headsets, adapter
    - USB cable
    - NARC1 PC, power supply
      - Keyboards (BT & USB)
      - Mice (BT & USB)
    - Audio splitter, power supply
    - Radio stand
  - [x] Bin 2 (teal): Station 2
    - Radio & power cable
    - Hand mic, foot switch, adapter
    - CW paddles
    - 2x headsets, adapter (W3TM has)
    - Audio splitter, power supply
    - NARC2 PC, power supply
      - Keyboards (BT & USB)
      - Mice (BT & USB)
  - [x] Bin 3 (black): PC monitors
    - 3x monitors
    - 2x arms, monitor power supply, HDMI
    - 2x stands
    - 1x power supply
  - [x] 4x folding tables (W3EDP to his house to hose down)
  - [x] 4-5x folding chairs (W3EDP to his house to hose down)
  - [x] Coax
    - New in bag 75' and 50' RG-213/8U
    - New in bag 75' and 50` RG-8x (W3EDP loan)
    - Bin with patch cables
  - [x] Bandpass filters
  - [x] Bin 4 (black): Club memorabilia
    - Banner
    - Plaques
  - [x] Office supplies
  - [x] Cleaning supplies
  - [x] Food & drink supplies
  - [x] Trash barrel
  - [x] Paracord spool

### Field Day Weekend (June 26 - 28)

#### Friday, June 26

- [ ] Supervise porta-john placement (K3CWP)

#### Saturday, June 27

- 08:30a EDT
  - Meet at mountaintop, load-in (W3TM, KC3MVL, KD3CCO)
    - 6x rolling chairs
    - Bins, trashcan
- 09:00a EDT (approx)
  - Leave mountaintop for Pleasant Gap
- 09:30a EDT (approx)
  - Arrive Pleasant Gap (W3TM, KC3MVL, KD3CCO, W3EDP, K3YV, N3LI)
  - [ ] Set-up antennas (W3EDP, K3YV, W3TM, KC3MVL, N3LI)
    - Air cannon (N3LI)
    - Antennas & support masts (W3EDP, K3YV)
    - Coax from mountain
  - [ ] Set-up station
    - Tables
    - Set up power
      - AC power strips
      - Extension cords as needed
- 10:00 EDT (approx)
  - Set up radios (W3TM, N3LI)
    - [ ] Station 1
      - Computer (NARC1)
        - Monitor + power + HDMI
        - Mouse
        - Mouse pad
        - Keyboard
        - Power
        - Networking cable
      - Radio
        - IC-7610
        - Power supply
        - Mic
        - Paddles
        - USB cable to computer
        - Headset/audio
        - Footswitch
      - [ ] Station 2
        - Computer (NARC2)
          - Monitor
          - Mouse
          - Mouse pad
          - Keyboard
          - Power
          - Networking cable
        - Radio
          - FT-710
          - Power supply
          - Mic
          - Paddles
          - USB cable to computer
          - Headset/audio
      - [ ] Station 3 (VHF/UHF) (W3SWL)
        - Computer (NARC3 loaned by W3TM)
          - Monitor + power + HDMI
          - Mouse (W3TM)
          - Mouse pad
          - Keyboard (W3TM)
          - Power
          - Networking cable (W3EDP or N3LI)
        - Radio (W3SWL)
          - IC-7100
          - Power supply
          - USB cable to computer
          - Mic
  - [ ] Setup network (N3LI)
    - Switch
    - Power supply
    - Cables
- 10:30 EDT
  - [ ] Set up food/info-table pop-up tents
  - [ ] Set up tarps
  - [ ] Set up info table
  - [ ] Buy ice (KD3AQC)
- 11:00 EDT (approx)
  - [ ] Test networked logging on NARC3 (N3LI)
    - [ ] Phone
    - [ ] CW
    - [ ] WSJT-X
    - [ ] fldigi
  - Connections to antennas
    - Bandpass filters
      - 2x patch cables
      - 2x barrel connectors
  - Coax to antenna
- 11:30 am (approx)
  - [ ] Set up lunch
    - [ ] Pick up lunch (Mike's Shiloh Road)

::: {.callout-warning}
**2:00 PM EDT (1800 UTC) Field Day begins**
:::

- [ ] Host educational activity. Time TBD. 
- [ ] Pick-up pizza. Time TBD.

#### Sunday, June 28

::: {.callout-warning}
**2:00 PM EDT (1800 UTC) Field Day ends**
:::

### Week after

- [ ] Clean logs and submit to ARRL. (N3LI)
