---
title: "Stations"
---

## About

This page describes some details about our Field Day stations.

## Class

Based on the results of the [survey](survey.qmd#visualizing), we plan to operate two (2) transmitters.

::: {.callout-note}
## Get on the Air (GOTA) station

On 2026-05-26 the Board discussed whether to mount a GOTA station this year.
We decided to use one of our transmitters specifically for helping new operators or inactive operators get on the air.
:::

We will operate at 100 W and use W3YA as our callsign.

## Radios

Our plan is to configure separate radios for phone, digital modes, and CW.
Radios configured for CW and digital modes have some special characteristics that make it more difficult to switch in the field.

### NARC1

- ICOM IC-7610 transceiver
- New mini-PC with external display
- Halibut Electronics audio interface
- ICOM SM-50 mic

### NARC2

- FlexRadio Flex 6400M
- HP All-in-one PC with 2nd Display
- KPA-1500 amplifier/ATU
- Halibut Electronics audio interface
- Inrad mic

The NARC2 Flex 6400 may not be the best field radio.
The Flex is not familiar to most club members, and can pose challenges to configure properly.

It may be more productive to bring a member's personal rig or purchase a radio for Field Day.

::: {.callout-note}
## Yaesu FT-710 Field

K3JHG has offered to loan the club a Yaesu FT-710 Field for use at Field Day.
:::

## Filters

The club owns bandpass filters for 75m/80m, 40m, 20m, 15m, and 10m.
All radios will use bandpass filters on Field Day.

## Antennas

::: {.callout-note}
## Work-in-progress
The antenna plan is still under discussion.

One possibility is to use W3TM's self-supporting 40m/75m NVIS antenna for 40m and 75m/80m.
For 20m, 15m, and 10m, we'd use an end-fed-half-wave (EFHW) loaned by a member.

W3TM, W3EDP, and K3YV have various masts, and tripods to enable Field Day attendees to erect antennas of their choosing.
:::

<!-- - 2x Mosley Triband Yagis, one pointed south, the other pointed west. These antennas will be for 20m, 15m, and 10m. -->
<!-- - 1 80m-10m EFHW antenna. This antenna is primarily for 40m and 75m/80m operation. -->
