project:
  type: website
  output-dir: "../docs"
website:
  title: "NARC Field Day"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - stations.qmd
      - calendar.qmd
      - people.qmd
      - planning.qmd
      
format:
  html:
    theme: cosmo
    css: include/css/styles.css
    toc: true

editor: source

